"""
Advanced AI Detection Module for Django
Detects AI-generated, copied, or translated content
"""
import re
import numpy as np
from typing import Tuple, List, Dict


class AdvancedAIDetector:
    """
    Advanced AI detection focusing on:
    - Copied content from AI tools
    - Translated content using AI
    - Pattern matching for AI-generated text
    """
    
    def __init__(self):
        # AI-generated text patterns (common in ChatGPT, etc.)
        self.ai_phrases = [
            r'\b(furthermore|moreover|in conclusion|to summarize)\b',
            r'\b(it is worth noting|one might argue|it can be observed)\b',
            r'\b(additionally|consequently|therefore|thus|hence)\b',
            r'\b(in essence|to put it simply|in other words)\b',
            r'\b(it is important to note|it should be noted)\b',
            r'\b(it is crucial to|it is essential to|it is vital to)\b',
        ]
        
        # Translation tool markers
        self.translation_markers = [
            r'\b(translated by|translation:|google translate|deepl|yandex translate)\b',
            r'\[.*?translat.*?\]',
            r'\(.*?translat.*?\)',
        ]
        
        # Copy/paste markers
        self.copy_markers = [
            r'\[.*?copied.*?\]',
            r'\(.*?source.*?\)',
            r'generated by',
            r'created by ai',
            r'written by chatgpt',
            r'written by gpt',
        ]
        
        # Sophisticated vocabulary (often from AI)
        self.sophisticated_vocab = [
            'paradigm', 'facilitate', 'utilize', 'implement', 'comprehensive',
            'substantial', 'significant', 'considerable', 'noteworthy',
            'remarkable', 'exemplify', 'demonstrate', 'illustrate', 'elucidate'
        ]
        
        self.transition_words = [
            'furthermore', 'moreover', 'additionally', 'consequently',
            'therefore', 'thus', 'hence', 'accordingly', 'subsequently'
        ]
    
    def analyze_text_statistics(self, text: str) -> Dict:
        """Analyze statistical features of text"""
        sentences = re.split(r'[.!?]+', text)
        sentences = [s.strip() for s in sentences if s.strip()]
        
        if not sentences:
            return {}
        
        words = text.split()
        word_lengths = [len(w) for w in words]
        sentence_lengths = [len(s.split()) for s in sentences]
        
        stats = {
            'avg_word_length': float(np.mean(word_lengths)) if word_lengths else 0,
            'avg_sentence_length': float(np.mean(sentence_lengths)) if sentence_lengths else 0,
            'sentence_length_std': float(np.std(sentence_lengths)) if len(sentence_lengths) > 1 else 0,
            'total_sentences': len(sentences),
            'total_words': len(words),
            'unique_words_ratio': len(set(words)) / len(words) if words else 0
        }
        
        return stats
    
    def detect_translation(self, text: str) -> Tuple[bool, List[str]]:
        """Detect if text was translated using AI tools"""
        text_lower = text.lower()
        detected = []
        
        for pattern in self.translation_markers:
            if re.search(pattern, text_lower, re.IGNORECASE):
                detected.append('TRANSLATION_TOOL')
        
        # Check for perfect grammar in translation (often AI)
        if len(text) > 100:
            # Very consistent sentence structure suggests AI translation
            sentences = re.split(r'[.!?]+', text)
            if len(sentences) > 3:
                lengths = [len(s.split()) for s in sentences if s.strip()]
                if lengths:
                    std_dev = float(np.std(lengths))
                    if std_dev < 10:  # Very consistent
                        detected.append('PERFECT_TRANSLATION')
        
        return len(detected) > 0, detected
    
    def detect_copy(self, text: str) -> Tuple[bool, List[str]]:
        """Detect if text was copied from AI"""
        text_lower = text.lower()
        detected = []
        
        for pattern in self.copy_markers:
            if re.search(pattern, text_lower, re.IGNORECASE):
                detected.append('COPY_MARKER')
        
        # Check for AI signature patterns
        ai_signatures = [
            'as an ai language model',
            'i am an ai',
            'i cannot',
            'i don\'t have',
            'i\'m designed to',
        ]
        
        for sig in ai_signatures:
            if sig in text_lower:
                detected.append('AI_SIGNATURE')
        
        return len(detected) > 0, detected
    
    def detect_patterns(self, text: str) -> Tuple[int, List[str]]:
        """Detect AI indicator patterns"""
        text_lower = text.lower()
        matches = 0
        detected_patterns = []
        
        for pattern in self.ai_phrases:
            found = re.findall(pattern, text_lower, re.IGNORECASE)
            if found:
                matches += len(found)
                detected_patterns.append('AI_PHRASE')
        
        # Check for sophisticated vocabulary
        sophisticated_count = sum(1 for word in self.sophisticated_vocab if word in text_lower)
        if sophisticated_count >= 3:
            matches += 2
            detected_patterns.append('SOPHISTICATED_VOCAB')
        
        # Check for excessive transition words
        transition_count = sum(1 for word in self.transition_words if word in text_lower)
        if transition_count >= 5:
            matches += 1
            detected_patterns.append('EXCESSIVE_TRANSITIONS')
        
        return matches, detected_patterns
    
    def calculate_ai_confidence(self, text: str) -> float:
        """
        Calculate confidence score (0-1) that text is AI-generated/copied/translated
        """
        if not text or len(text.strip()) < 30:
            return 0.0
        
        confidence = 0.0
        text_lower = text.lower()
        
        # Check for translation markers (high confidence)
        is_translated, translation_patterns = self.detect_translation(text)
        if is_translated:
            confidence += 0.6
            if 'PERFECT_TRANSLATION' in translation_patterns:
                confidence += 0.2
        
        # Check for copy markers (very high confidence)
        is_copied, copy_patterns = self.detect_copy(text)
        if is_copied:
            confidence += 0.7
            if 'AI_SIGNATURE' in copy_patterns:
                confidence = 1.0  # Definite AI
        
        # Pattern detection
        pattern_matches, patterns = self.detect_patterns(text)
        if pattern_matches >= 5:
            confidence += 0.3
        elif pattern_matches >= 3:
            confidence += 0.2
        elif pattern_matches >= 2:
            confidence += 0.1
        
        # Statistical analysis
        stats = self.analyze_text_statistics(text)
        
        # Very consistent sentence length (AI characteristic)
        if stats.get('sentence_length_std', 100) < 12 and stats.get('total_sentences', 0) > 3:
            confidence += 0.15
        
        # High average sentence length (AI often writes longer sentences)
        if stats.get('avg_sentence_length', 0) > 20:
            confidence += 0.1
        
        # Check for explicit AI markers
        if '[ai enhanced' in text_lower or '[ai assisted' in text_lower or 'chatgpt' in text_lower:
            confidence = 1.0
        
        return min(confidence, 1.0)
    
    def detect(self, text: str) -> Dict:
        """
        Main detection method
        Returns: {
            'is_ai_used': bool,
            'confidence': float,
            'patterns': List[str],
            'statistics': dict,
            'detection_type': str  # 'copy', 'translation', 'generated', or 'none'
        }
        """
        if not text or len(text.strip()) < 30:
            return {
                'is_ai_used': False,
                'confidence': 0.0,
                'patterns': [],
                'statistics': {},
                'detection_type': 'none'
            }
        
        # Check for copy first (highest priority)
        is_copied, copy_patterns = self.detect_copy(text)
        if is_copied:
            confidence = self.calculate_ai_confidence(text)
            return {
                'is_ai_used': True,
                'confidence': min(confidence, 1.0),
                'patterns': copy_patterns,
                'statistics': self.analyze_text_statistics(text),
                'detection_type': 'copy'
            }
        
        # Check for translation
        is_translated, translation_patterns = self.detect_translation(text)
        if is_translated:
            confidence = self.calculate_ai_confidence(text)
            return {
                'is_ai_used': True,
                'confidence': min(confidence, 1.0),
                'patterns': translation_patterns,
                'statistics': self.analyze_text_statistics(text),
                'detection_type': 'translation'
            }
        
        # General AI detection
        confidence = self.calculate_ai_confidence(text)
        _, patterns = self.detect_patterns(text)
        stats = self.analyze_text_statistics(text)
        
        is_ai_used = confidence >= 0.4
        
        return {
            'is_ai_used': is_ai_used,
            'confidence': round(confidence, 3),
            'patterns': patterns,
            'statistics': stats,
            'detection_type': 'generated' if is_ai_used else 'none'
        }


# Export singleton instance
ai_detector = AdvancedAIDetector()
