# Generated by Django 4.2.7 on 2026-02-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Sayt logotipi', null=True, upload_to='site/')),
                ('site_name', models.CharField(default='Fast Education', max_length=200)),
                ('tagline', models.CharField(default='English Language Assessment Centre', max_length=300)),
                ('certificate_bg', models.ImageField(blank=True, help_text='Sertifikat fon rasmi', null=True, upload_to='site/')),
                ('certificate_stamp', models.ImageField(blank=True, help_text='Sertifikat muhri/shtampi', null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
