# Generated by Django 4.2.7 on 2026-03-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Kirish sahifasi fon rasmi', null=True, upload_to='site/'),
        ),
    ]
